apiVersion: v1
kind: Service
metadata:
  name: traefik
spec:
  selector:
    app: traefik
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      name: http
      nodePort: 30000
    - port: 8081
      targetPort: 8081
      name: metrics
      nodePort: 30001
